version: '3.8'

services:
  safety-net-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./configs:/app/configs
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Development environment with hot reloading
  safety-net-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "3001:3000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./configs:/app/configs
      - ./reports:/app/reports
    command: >
      sh -c "
      cd /app/backend && python app.py &
      cd /app/frontend && npm run dev
      "
    restart: unless-stopped