name = "safety-net-analysis"
compatibility_date = "2024-01-15"

[env.production]
account_id = ""

[[routes]]
pattern = "safety-net-analysis.pages.dev"
custom_domain = false

[site]
bucket = "./dist"
entry-point = "workers-site"